# Generated by Django 5.0.6 on 2024-06-22 17:43

import datetime
import django.db.models.deletion
import django_quill.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductServicesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('slug', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('image', models.FileField(blank=True, default='', null=True, upload_to='category')),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('price_currency', models.CharField(blank=True, choices=[('₹', '₹'), ('$', '$'), ('€', '€')], default='', max_length=100, null=True)),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('length', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('experties_level', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('open_time', models.TimeField(verbose_name=datetime.time(10, 0))),
                ('close_time', models.TimeField(verbose_name=datetime.time(18, 0))),
                ('description', django_quill.fields.QuillField(blank=True, default='', null=True)),
                ('slug', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='service_category', to='services.productservicescategory')),
            ],
        ),
    ]
