# Generated by Django 5.0.6 on 2024-06-23 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productservices',
            name='is_home',
            field=models.BooleanField(default=True),
        ),
    ]
