# Generated by Django 5.0.6 on 2024-06-23 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_productservices_is_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='productservices',
            name='image',
            field=models.FileField(blank=True, default='', null=True, upload_to='category'),
        ),
    ]
