# Generated by Django 5.0.6 on 2024-06-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_productservices_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productservices',
            name='is_home',
            field=models.BooleanField(default=False),
        ),
    ]
